[tool.black]
line-length = 79
target-version = ['py38']

[tool.isort]
multi_line_output = 3
include_trailing_comma = true
force_grid_wrap = 2
use_parentheses = true
order_by_type = false
combine_as_imports = true
